### ISSUE TITLE
java.lang.NoSuchFieldError: usedNames

### ISSUE THREAD

**Issue by tdugger** [VazkiiModsArchive/GenCreator#9]
Tried running World Automation pack from TechnicLauncher.  Get this error.  Running on Ubuntu 14.

java.lang.NoSuchFieldError: usedNames
        at vazkii.gencreator.DataStorage.<clinit>(DataStorage.java:34)
        at vazkii.gencreator.world.GCWorldGenerator.generate(GCWorldGenerator.java:47)
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:438)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1202)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:293)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:199)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:167)
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:480)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
        at java.lang.Thread.run(Thread.java:745)

**Comment by tdugger** [comment]
This was actually fixed by @planetguy32 in is patch-1 branch.  You should accept his pull request.
In my fork I got this building with gradle.

**Comment by Its-Patchi** [comment]
XCompWiz/Mystcraft-Issues/issues/151
Also affects Mystcraft
